### ISSUE TITLE
Error: code "unimplemented"

### ISSUE THREAD

**Issue by DercilioFontes** [migtam628/capacitor-ios-app-tracking#13]
Hi guys,

I'm trying to use the package in an Ionic project with React and I am getting this error when it calls the `requestPermission` method.

<img src="https://user-images.githubusercontent.com/20172847/127247369-341e4985-66c0-4a70-917a-bd45c815120a.jpg" alt="Error unimplemented" width="200"/> 

I am out of ideas of what is causing this.

Capacitor says that:

> Unimplemented
>
>Use this error to indicate that a method can’t be implemented for iOS.

```swift
@objc override func methodThatRequiresAndroid(_ call: CAPPluginCall) {
    call.unimplemented("Not implemented on iOS.")
}
```
https://capacitorjs.com/docs/plugins/ios#unimplemented

It seems weird to me.

Any help?

**Config**

> Ionic:
>    Ionic CLI       : 6.16.3 (/usr/local/lib/node_modules/@ionic/cli)
>    Ionic Framework : @ionic/react 5.6.12
> 
> Capacitor:
>    Capacitor CLI      : 3.1.2
>    @capacitor/android : 3.1.2
>    @capacitor/core    : 3.1.2
>    @capacitor/ios     : 3.1.2
> 
> Utility:
>    cordova-res : 0.15.3
>    native-run  : 1.4.0
> 
> System:
>    NodeJS : v16.4.0 (/usr/local/bin/node)
>    npm    : 7.20.1
>    OS     : macOS Big Sur

**Comment by migtam628** [comment]
can you please share your code.
I tested today and it seems to be working fine.

also dont forget to add the NSUserTrackingUsageDescription key to the info.plist.

![image](https://user-images.githubusercontent.com/26477083/127411305-903209ea-5142-4cde-ba93-f0a37cad41f9.jpeg)

**Comment by DercilioFontes** [comment]
Hi,

I added the NSUserTrackingUsageDescription key to the info.plist.

The code was this:

```javascript
import { AppTrackingTransparency, IOSAppTrackingStatus } from "capacitor-ios-app-tracking";

...

export const useIosUserPermission = () => {
    const dispatch = useDispatch();
    const [userPermission, setUserPermission] = useState<IOSAppTrackingStatus>();
    
    useEffect(() => {  
        const requestUserPermission = async () => {
           try {
             const { status } = await AppTrackingTransparency.requestPermission();
             setUserPermission(status);
           } catch (error) {
             dispatch(showAlert("getUserPermission error!", JSON.stringify(error, null, 2)));
           }
         };
         
         if (!userPermission || userPermission === "unrequested") {
           requestUserPermission();
         }
       }, [dispatch, userPermission]);
       
     useEffect(() => {
       const getUserTrackingStatus = async () => {
         try {
           const { status } = await AppTrackingTransparency.getTrackingStatus();
           setUserPermission(status);
         } catch (error) {
           dispatch(showAlert("getUserPermission error!", JSON.stringify(error, null, 2)));
         }
       };
         
         getUserTrackingStatus();
   }, [dispatch]);

return userPermission;
};
```

**Comment by migtam628** [comment]
Hey I tested your code and it works fine.
Try cleaning project. 

- rm node_modules and npm install

- rm ios && npx cap add ios && npx cap update

and try it again, it should be working. I'm not quite sure why you're receiving that error message.

**Comment by DercilioFontes** [comment]
Ok. Thank you. I really don't understand why it wouldn't work. I'll try that.

**Comment by migtam628** [comment]
Sounds good, just let me know of your progress.

Ill be here if you need anything.

**Comment by DercilioFontes** [comment]
I tried it in the simulator and on my iPhone, and I still get the same error. It's hard to find out what is happening. But thank you for you're feedback.

I used another package and it worked. It was https://www.npmjs.com/package/capacitor-app-tracking-transparency
